spring.datasource.url=jdbc:postgresql://postgres:5432/dinowiki
spring.datasource.username=dinouser
spring.datasource.password=dinopass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
spring.sql.init.mode=never
spring.web.resources.static-locations=classpath:/static/,file:images/,file:../